# /etc/netplan/static.yaml

network:
  version: 2
  ethernets:
    eth0:
      dhcp4: false
      addresses:
        - 10.0.10.3/24
      gateway4: 10.0.10.1
      nameservers:
        addresses: [192.168.178.1]
